<?php
/**
 * Created by PhpStorm.
 * User: Julius Alvarado
 * Date: 8/25/2019
 * Time: 2:35 AM
 *
 *
 * - This is the VERY simple UI so the user can type something
 * a textarea input form to emulate client and data instructions
 *
 * Primarily this is good for a human to test, not phpunit.
 *
 */

$appName = "Code Buddies Connect";

?>


<!DOCTYPE html>

<html lang="en" data-ng-app="cbConnectApp">

<head>
    <meta charset="UTF-8">
    <title>Code Buddies connect</title>

    <!-- Angular Material CSS now available via Google CDN; version 1.1.9 used here -->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.9/angular-material.min.css">
    <link rel="stylesheet" href="/ui-match/styles/app.css">

    <!-- ng-cloak -->
    <style type="text/css">
        [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {
            display: none !important;
        }
    </style>
</head>


<body ng-controller="MatchCtrl">

<!-- Horizontal sort of Nav Bar -->
<md-toolbar>
    <div class="md-toolbar-tools">
        <h2 flex md-truncate> Code Buddies Connect</h2>
        <md-button class="md-raised md-accent md-hue-3 cb-btn" aria-label="Learn More">
            Learn More
        </md-button>
        <md-button class="md-fab md-mini md-hue-3 cb-pad5" aria-label="Favorite">
            <ng-md-icon icon="favorite" size="30" fill="#ffffff"></ng-md-icon>
        </md-button>
    </div>
</md-toolbar>

<div layout="row" layout-align="center center">
    <!-- LEFT side -->
    <div layout-padding flex="15">
        <!-- icon about -->
        <div layout="row" layout-align="center center">
            <ng-md-icon icon="face" style="fill: sandybrown" size="36"></ng-md-icon>
            <h1>&nbsp; About</h1>
        </div>
        
        <h1 class="cb-text-center cb-mtop-0">2 / 3 <ng-md-icon icon="check_circle" style="fill: hotpink"></ng-md-icon></h1>
    </div>

    <!-- RIGHT side -->
    <div class="md-padding" flex="60">
        <form action="/test/get-matched/contact-info" method="post">
            <h1>About you and your skills</h1>
            <br>
            <!-- Users' name -->
            <md-input-container class="md-block">
                <label for="user-name">Hello, what is your name?</label>
                <input id="user-name" name="user-name" type="text">
            </md-input-container>

            <br><br>

            <!-- One line intro -->
            <md-input-container class="md-block">
                <label for="one-line-intro">Your 1 line intro about yourself?</label>
                <input type="text" id="one-line-intro" name="one-line-intro">
            </md-input-container>

            <br><br>

            <!-- User Skills -->
            <md-input-container class="md-block">
                <label for="user-skills">What skill(s) can you help others with?</label>
                <input id="user-skills" name="user-skills" type="text">
            </md-input-container>

            <br><br>

            <!-- Want to improve Skills -->
            <md-input-container class="md-block">
                <label for="want-to-improve-skills">What skill(s) are you trying to improve?</label>
                <input type="text" id="want-to-improve-skills" name="want-to-improve-skills">
            </md-input-container>

            <input type="hidden" name="app-name" value="<?= $appName ?>">

            <div layout="row" layout-align="end start">
                <md-button class="md-raised md-accent md-hue-4 cb-btn" type="submit">
                    Get Matched
                </md-button>
            </div>
        </form>
    </div>
</div>

<!-- Sample Input
<div layout="row" layout-align="center center">
    <h2>sample skills to copy and paste (or type in your own input)</h2>

    <ul>
        <li>math, css, javascript, python</li>
        <li>apache, excel, math, visual basic, data, python</li>
        <li>interview practice, java, go, c, hack, r</li>
        <li>c, interview practice, game</li>
    </ul>
</div>
-->

<br><br>

<!-- Footer -->
<footer layout="row" layout-padding layout-margin layout-align="center start">
    <div flex="25">
        <p>Get matched with a mentor, mentee, collaborator, or pair programming partner.</p>
    </div>
    <div flex="50">
        <h1 class="cb-text-center cb-mtop-0"> <?= $appName ?></h1>
        <h2 class="cb-text-center"> &copy; 2020</h2>
    </div>
    <div flex="25">
        <a href="https://codebuddies.org/">
            <md-button class="cb-btn">Codebuddies.org</md-button>
        </a>
        <a href="mailto:j.alvarado@engineer.com">
            <md-button class="cb-btn">j.alvarado@engineer.com</md-button>
        </a>
        <a href="https://github.com/ideaguy3d/cb-connect">
            <md-button class="cb-btn">GitHub repo</md-button>
        </a>
    </div>
</footer>


<!-- Angular Material Dependencies -->
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.2/angular.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.2/angular-animate.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.2/angular-aria.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.7.2/angular-messages.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular-material-icons/0.7.1/angular-material-icons.min.js"></script>

<!-- Angular Material Javascript now available via Google CDN; version 1.1.9 used here -->
<script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.9/angular-material.min.js"></script>

<!-- The AngularJS 1.7 app -->
<script src="/ui-match/app.js"></script>


</body>
</html>